name = "belote-worker"
main = "index.ts"
compatibility_date = "2024-02-23"

# Configuration KV pour le cache
kv_namespaces = [
  { binding = "GAMES_CACHE", id = "ID_GÉNÉRÉ_PAR_KV_CREATE" }
]

# Configuration D1 pour SQLite
[[d1_databases]]
binding = "DB"
database_name = "belote-db"
database_id = "ID_GÉNÉRÉ_PAR_D1_CREATE"

# Configuration des WebSockets
[durable_objects]
bindings = [
  { name = "GAMES", class_name = "GameDurableObject" }
]

# Configuration de développement
[dev]
port = 8787